# EE Calculation from Scratch

Here's another (correct) way to calculate the EE,

First we will make a system where we describe the random variable states from a value of $[0, 1]$

$$
\ket{\psi} = \begin{pmatrix} 0.38 \\ 0.45 \\ 0.56 \\ \vdots \end{pmatrix}
$$

where the length of the column matrix is $N = 2^{n}$, with $n$ as the number of qubits we want to study and calculate the entanglement entropy.
Now that we have a random statevector, we would like to re-write it as a combination of its basis, 

$$
\ket{\psi} = \begin{pmatrix} 0.38 \\ 0.45 \\ 0.56 \\ \vdots \end{pmatrix} = 0.38 \begin{pmatrix} 1 \\ 0 \\ 0 \\ \vdots \end{pmatrix} + 0.45 \begin{pmatrix} 0 \\ 1 \\ 0 \\ \vdots \end{pmatrix} + 0.56 \begin{pmatrix} 0 \\ 0 \\ 1 \\ \vdots \end{pmatrix} + \cdots.
$$

We would need to normalize the statevector by taking $\rho = \sum_i a_i a^*_i\ket{i}\bra{i} = 1$.
Lets realize this into python,

In [3]:
def psi_initial_random_state(nQubits = 8, min_val = 0, max_val = 1):
    """
    Generate a row vector of random zeros and ones, and then each of the components are multiplied by a constant taken from a Gaussian ensemble
    for each of the components of the statevector.

    Parameters:
    nQubits (int): The length of the vector which corresponds to how many qubits.

    Returns:
    numpy.ndarray: A row vector of random numbers from [0, 1].
    """
    if not isinstance(nQubits, int) or nQubits <= 0:
        raise ValueError("The number of qubits must be a positive integer.")
    gaussian_ensemble = np.random.uniform(min_val, max_val, size = (nQubits, 1))
    #print(f"The gaussian ensemble for each of the components: \n", gaussian_ensemble)
    return gaussian_ensemble 

In [ ]:
test_psi_initial_random_state = psi_initial_random_state(4)
test_psi_initial_random_state

array([[0.26709936],
       [0.39991554],
       [0.82016734],
       [0.52639184]])

now that we have a random state $\ket{\psi}$, we want to normalize the state so that $\rho = \sum_{ij} a_i a^*_j \ket{i}\bra{j} =1 $.

In [4]:
def normalize(matrix):
    norm = np.linalg.norm(matrix)
    matrix = matrix/norm  # normalized matrix
    return matrix
    return norm_arr

In [6]:
normalized_test_psi_initial_random_state = normalize(test_psi_initial_random_state)
print(f"Here's the normalized random state :\n",normalized_test_psi_initial_random_state)
Y = normalized_test_psi_initial_random_state*normalized_test_psi_initial_random_state
print(f"and here's the sum of the normalized density matrix :\n",sum(Y))

<class 'NameError'>: name 'test_psi_initial_random_state' is not defined

Okay, now that we have a normalized statevector, we can start to translate each of the components of the matrix into a binary number which corresponds to the state of the system.

For example, for an nQubit column vector, we have the first component symbolized as `psi[0]` with a certain normalized constant of $a_{[0]}$, as in python, the first component have the index of 0. This would represent the following state,
$$
\psi[0] \rightarrow a_{[0]}\ket{00000\cdots 00},
$$
where the length of the ket is nQubits.

and for $\psi_{[1]}$, it would correspond a state of,
$$
\psi[1] \rightarrow a_{[1]}\ket{00000\cdots 01},
$$
and so on. Here it is clear that our system just use the index of the array and translate it into binary that will correspond into the actual quantum state.
Before thinking about how to separate the system into 2 sub-system, lets translate it first.

From Vinay's explanation, the first step I want to do is to determine the size of subsystem A and B as $n_A$ and $n_B$ respectively.

So for a system with a total of 4 qubits, I want to start from $n_A = 1$ and $n_B = 3$, where I would need to create a basis with the size of $2^{n_A}$ and $2^{n_B}$.


In [8]:
import numpy as np
n_A = 1
n_B = 3

Creating the basis

In [9]:
basis_A = np.random.uniform(0, 1, (2**n_A, 1))
print(f"Basis for subsystem A :\n",basis_A)
basis_B = np.random.uniform(0, 1, (2**n_B, 1))
print(f"Basis for subsystem B :\n",basis_B)

Basis for subsystem A :
 [[0.54496736]
 [0.32215501]]
Basis for subsystem B :
 [[0.50744557]
 [0.80379004]
 [0.97060235]
 [0.85036099]
 [0.03134757]
 [0.99900947]
 [0.36095748]
 [0.91579099]]


In [10]:
Psi_AB = np.kron(basis_A, basis_B)
print(f"State of 'Psi' as kronecker product of basis A and B :\n",
      Psi_AB)

State of 'Psi' as kronecker product of basis A and B :
 [[0.27654127]
 [0.43803933]
 [0.5289466 ]
 [0.46341898]
 [0.0170834 ]
 [0.54442755]
 [0.19671004]
 [0.49907619]
 [0.16347613]
 [0.25894499]
 [0.31268441]
 [0.27394805]
 [0.01009878]
 [0.3218359 ]
 [0.11628426]
 [0.29502665]]


In [11]:
len(Psi_AB)

16

Normalizing the column vector (State of $\Psi$)

In [13]:
norm = np.linalg.norm(Psi_AB)

# Normalize the vector
normalized_Psi_AB_test = Psi_AB / norm
print(f"The normalized state of Psi :\n", normalized_Psi_AB_test)

The normalized state of Psi :
 [[0.20508751]
 [0.32485709]
 [0.3922754 ]
 [0.34367905]
 [0.01266933]
 [0.40375633]
 [0.14588337]
 [0.37012302]
 [0.12123656]
 [0.19203781]
 [0.23189184]
 [0.20316433]
 [0.00748942]
 [0.23867874]
 [0.0862383 ]
 [0.21879656]]


In [ ]:
d#ef Psi_indexed(i, j):
 #   if isinstance(i, int) and i > 0 and i <= len(basis_A) and isinstance(j, int) and j > 0 and j <= len(basis_B):
 #       return normalized_Psi_AB[(i-1) * len(basis_B) + (j-1)]
 #   else:
 #       return ValueError("Indices are out of bounds or not integers.")

In [24]:
def Psi_indexed_v2(normalized_matrix, i, j):
    if isinstance(i, int) and i > 0 and i <= 2**n_A and isinstance(j, int) and j > 0 and j <= 2**n_B:
        return normalized_matrix[(i - 1) * 2**n_B + (j - 1)]
    else:
        return ValueError("Indices are out of bounds or not integers")

In [40]:
Psi_indexed_v2(normalized_Psi_AB_test, 2, 1)

array([0.12123656])

In [ ]:
#def Psi_indexed_conjugate(k, l):
#    if isinstance(k, int) and k > 0 and k <= len(basis_A) and isinstance(l, int) and l > 0 and l <= len(basis_B):
#        return np.conjugate(normalized_Psi_AB[(k-1) * len(basis_B) + (l-1)])    

In [22]:
def Psi_indexed_conjugate_v2(normalized_matrix, k, l):
    if isinstance(k, int) and k > 0 and k <= 2**n_A and isinstance(l, int) and l > 0 and l <= 2**n_B:
        return np.conjugate(normalized_matrix[(k - 1) * 2**n_B + (l - 1)])
    else:
        return ValueError("Indices are out of bounds or not integers")

In [23]:
Psi_indexed_conjugate_v2(normalized_Psi_AB_test, k = 1, l = 1)

array([0.20508751])

In [ ]:
def Density_Matrix_Psi_AB(i, j, k, l):
    # Summing over Psi(i,j) and Psi*(k, j), sum over J from 1 to the len(basis_B).
    Density_Matrix_Psi_AB = Psi_indexed(i, j) * Psi_indexed_conjugate(k, l)
    return Density_Matrix_Psi_AB[0]

In [ ]:
def Partial_Trace_Subsystem_B(i, k):
    result = 0
    for j in range(len(basis_B)):
        result += Density_Matrix_Psi_AB(i, (j+1), k, (j+1))
    return result
        

In [ ]:
 range(1,8-1)

range(1, 7)

In [ ]:

    matrix = np.zeros((len(basis_A), len(basis_A)))
    print(matrix)

[[0. 0.]
 [0. 0.]]


In [ ]:
def Partial_Trace_Subsystem_B_array_test():
    matrix = np.zeros((len(basis_A), len(basis_A)))
    
    for i in range(len(basis_A) - 1):
        for k in range(len(basis_A) - 1):
            matrix[i, k] = Partial_Trace_Subsystem_B((i + 1), (k + 1))
    return print(matrix)

In [ ]:
def f(i, k):
    return Partial_Trace_Subsystem_B(i, k)

# Simple ranges
i_range = range(1,len(basis_A)+1 )  # i = 0, 1
k_range = range(1,len(basis_A) +1)  # j = 0, 1

# Create the matrix
matrix = np.array([[f(i, k) for k in k_range] for i in i_range])
print(matrix)

[[0.42973814 0.49503866]
 [0.49503866 0.57026186]]


In [ ]:
print(i_range)

range(1, 3)


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)

[-1.11022302e-16  1.00000000e+00]


In [ ]:
testmatrix = ((0, 1), (3, 1))
#print(testmatrix)

row_vector = np.array((1, 2))
#print(row_vector)

vector = np.array(((1, 2), (3, 4)))
print(vector)

eigenvalue_test, eigen_bases = np.linalg.eig(vector)
print(eigenvalue_test)

[[1 2]
 [3 4]]
[-0.37228132  5.37228132]


In [ ]:
for i in eigenvalue_test:
    sum_of_EE = 0
    lambda_log_lambda = i * np.log(i)
    sum_of_EE += lambda_log_lambda
    print(sum_of_EE)


nan
9.032162188360221


C:\Users\Acer Aspire 5\AppData\Local\Temp\ipykernel_13424\1267295119.py:3: RuntimeWarning: invalid value encountered in log
  lambda_log_lambda = i * np.log(i)
